#include "nsISupports.idl"
#include "nsILDAPMessage.idl"
#include "nsILDAPConnection.idl"
#include "nsILDAPOperation.idl"

[scriptable, uuid(bb9bd3e8-11ec-4dae-9a38-c0278420e092)]
interface nsILdapDataSource: nsISupports {
    // attributes, constants, methods, ...

	attribute nsILDAPConnection mConnection;
	attribute nsILDAPOperation  mOperationBind; 
	attribute nsILDAPOperation  mOperationSearch;
	attribute long mFinished;

	void init();

	void getMessages(out unsigned long count, [array, size_is(count), retval] out nsILDAPMessage retv );

	void getMessagesEntry(out unsigned long count, [array, size_is(count), retval] out nsILDAPMessage retv );
	
	unsigned long getMessagesEntryLength();
	nsILDAPMessage getMessagesEntryIndexBy(in unsigned long index);
  
	void query(in wstring aLdapUri, in wstring aBindName, in wstring password);

//                               out unsigned long count,
//                               [array, size_is(count), retval] out wstring completions
};
