#include "nsISupports.idl"
#include "nsIArray.idl"

[scriptable, uuid(bb9bd3e8-11ec-4dae-9a38-c0278420e092)]
interface ldapDataSource: nsISupports {
    // attributes, constants, methods, ...

	attribute nsIArray mMessages;
	attribute nsIArray mMessagesEntry;

	void init();
  
	void create(in wstring aLdapUri,
                               in wstring aBindName, in wstring password);




//                               out unsigned long count,
//                               [array, size_is(count), retval] out wstring completions
};
